//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.42.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="ReferenceDataSoap", Namespace="http://www.capitaliq.com/CIQDotNet/ReferenceData")]
public partial class ReferenceData : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback GetReferenceDataInfoOperationCompleted;
    
    /// <remarks/>
    public ReferenceData() {
        this.Url = "https://api.capitaliq.com/ciqdotnet/api/current/ReferenceData.asmx";
    }
    
    /// <remarks/>
    public event GetReferenceDataInfoCompletedEventHandler GetReferenceDataInfoCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.capitaliq.com/CIQDotNet/ReferenceData/GetReferenceDataInfo", RequestNamespace="http://www.capitaliq.com/CIQDotNet/ReferenceData", ResponseNamespace="http://www.capitaliq.com/CIQDotNet/ReferenceData", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public ReferenceDataInfo[] GetReferenceDataInfo(int inReferenceDataTypeID) {
        object[] results = this.Invoke("GetReferenceDataInfo", new object[] {
                    inReferenceDataTypeID});
        return ((ReferenceDataInfo[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetReferenceDataInfo(int inReferenceDataTypeID, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetReferenceDataInfo", new object[] {
                    inReferenceDataTypeID}, callback, asyncState);
    }
    
    /// <remarks/>
    public ReferenceDataInfo[] EndGetReferenceDataInfo(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((ReferenceDataInfo[])(results[0]));
    }
    
    /// <remarks/>
    public void GetReferenceDataInfoAsync(int inReferenceDataTypeID) {
        this.GetReferenceDataInfoAsync(inReferenceDataTypeID, null);
    }
    
    /// <remarks/>
    public void GetReferenceDataInfoAsync(int inReferenceDataTypeID, object userState) {
        if ((this.GetReferenceDataInfoOperationCompleted == null)) {
            this.GetReferenceDataInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetReferenceDataInfoOperationCompleted);
        }
        this.InvokeAsync("GetReferenceDataInfo", new object[] {
                    inReferenceDataTypeID}, this.GetReferenceDataInfoOperationCompleted, userState);
    }
    
    private void OnGetReferenceDataInfoOperationCompleted(object arg) {
        if ((this.GetReferenceDataInfoCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetReferenceDataInfoCompleted(this, new GetReferenceDataInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(LanguageReferenceDataType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(IndustryReferenceDataType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(GeographyReferenceDataType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(FormTypeReferenceDataType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ExchangeReferenceDataType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ExchangeGroupReferenceDataType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(DataItemReferenceDataType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(CurrencyReferenceDataType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(CountryReferenceDataType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ContributorReferenceDataType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(CalculationType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ReferenceDataWStringID))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(CompanyRelTypeReferenceDataType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(HoldingAdjustmentReferenceDataType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ScaleReferenceDataType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(StateReferenceDataType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(AnalystReferenceDataType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(RecommendationReferenceDataType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.capitaliq.com/CIQDotNet/ReferenceData")]
public partial class ReferenceDataInfo {
    
    private int referenceDataIDField;
    
    private string referenceDataNameField;
    
    /// <remarks/>
    public int ReferenceDataID {
        get {
            return this.referenceDataIDField;
        }
        set {
            this.referenceDataIDField = value;
        }
    }
    
    /// <remarks/>
    public string ReferenceDataName {
        get {
            return this.referenceDataNameField;
        }
        set {
            this.referenceDataNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.capitaliq.com/CIQDotNet/ReferenceData")]
public partial class LanguageReferenceDataType : ReferenceDataInfo {
    
    private string iSO639CodeField;
    
    /// <remarks/>
    public string ISO639Code {
        get {
            return this.iSO639CodeField;
        }
        set {
            this.iSO639CodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.capitaliq.com/CIQDotNet/ReferenceData")]
public partial class IndustryReferenceDataType : ReferenceDataInfo {
    
    private int subParentIdField;
    
    private int childLevelField;
    
    /// <remarks/>
    public int SubParentId {
        get {
            return this.subParentIdField;
        }
        set {
            this.subParentIdField = value;
        }
    }
    
    /// <remarks/>
    public int ChildLevel {
        get {
            return this.childLevelField;
        }
        set {
            this.childLevelField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.capitaliq.com/CIQDotNet/ReferenceData")]
public partial class GeographyReferenceDataType : ReferenceDataInfo {
    
    private int subParentIdField;
    
    private int childLevelField;
    
    /// <remarks/>
    public int SubParentId {
        get {
            return this.subParentIdField;
        }
        set {
            this.subParentIdField = value;
        }
    }
    
    /// <remarks/>
    public int ChildLevel {
        get {
            return this.childLevelField;
        }
        set {
            this.childLevelField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.capitaliq.com/CIQDotNet/ReferenceData")]
public partial class FormTypeReferenceDataType : ReferenceDataInfo {
    
    private string formTypeDescriptionField;
    
    /// <remarks/>
    public string FormTypeDescription {
        get {
            return this.formTypeDescriptionField;
        }
        set {
            this.formTypeDescriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.capitaliq.com/CIQDotNet/ReferenceData")]
public partial class ExchangeReferenceDataType : ReferenceDataInfo {
    
    private string exchangeNameField;
    
    private string countryField;
    
    private string symbolField;
    
    /// <remarks/>
    public string ExchangeName {
        get {
            return this.exchangeNameField;
        }
        set {
            this.exchangeNameField = value;
        }
    }
    
    /// <remarks/>
    public string Country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
    
    /// <remarks/>
    public string Symbol {
        get {
            return this.symbolField;
        }
        set {
            this.symbolField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.capitaliq.com/CIQDotNet/ReferenceData")]
public partial class ExchangeGroupReferenceDataType : ReferenceDataInfo {
    
    private string exchangeGroupField;
    
    /// <remarks/>
    public string ExchangeGroup {
        get {
            return this.exchangeGroupField;
        }
        set {
            this.exchangeGroupField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.capitaliq.com/CIQDotNet/ReferenceData")]
public partial class DataItemReferenceDataType : ReferenceDataInfo {
    
    private int dataCollectionTypeIdField;
    
    private string dataCollectionTypeNameField;
    
    /// <remarks/>
    public int DataCollectionTypeId {
        get {
            return this.dataCollectionTypeIdField;
        }
        set {
            this.dataCollectionTypeIdField = value;
        }
    }
    
    /// <remarks/>
    public string DataCollectionTypeName {
        get {
            return this.dataCollectionTypeNameField;
        }
        set {
            this.dataCollectionTypeNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.capitaliq.com/CIQDotNet/ReferenceData")]
public partial class CurrencyReferenceDataType : ReferenceDataInfo {
    
    private int countryIDField;
    
    private string iSOCodeField;
    
    private bool majorCurrencyFlagField;
    
    private string symbolField;
    
    private bool activeFlagField;
    
    /// <remarks/>
    public int CountryID {
        get {
            return this.countryIDField;
        }
        set {
            this.countryIDField = value;
        }
    }
    
    /// <remarks/>
    public string ISOCode {
        get {
            return this.iSOCodeField;
        }
        set {
            this.iSOCodeField = value;
        }
    }
    
    /// <remarks/>
    public bool MajorCurrencyFlag {
        get {
            return this.majorCurrencyFlagField;
        }
        set {
            this.majorCurrencyFlagField = value;
        }
    }
    
    /// <remarks/>
    public string Symbol {
        get {
            return this.symbolField;
        }
        set {
            this.symbolField = value;
        }
    }
    
    /// <remarks/>
    public bool ActiveFlag {
        get {
            return this.activeFlagField;
        }
        set {
            this.activeFlagField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.capitaliq.com/CIQDotNet/ReferenceData")]
public partial class CountryReferenceDataType : ReferenceDataInfo {
    
    private int countryCodeField;
    
    private string countrySymbolField;
    
    private int primarySubTypeIdField;
    
    /// <remarks/>
    public int CountryCode {
        get {
            return this.countryCodeField;
        }
        set {
            this.countryCodeField = value;
        }
    }
    
    /// <remarks/>
    public string CountrySymbol {
        get {
            return this.countrySymbolField;
        }
        set {
            this.countrySymbolField = value;
        }
    }
    
    /// <remarks/>
    public int PrimarySubTypeId {
        get {
            return this.primarySubTypeIdField;
        }
        set {
            this.primarySubTypeIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.capitaliq.com/CIQDotNet/ReferenceData")]
public partial class ContributorReferenceDataType : ReferenceDataInfo {
    
    private int companyIDField;
    
    private int researchContributorStatusIDField;
    
    private bool hasResearchField;
    
    private bool hasEstimatesField;
    
    /// <remarks/>
    public int CompanyID {
        get {
            return this.companyIDField;
        }
        set {
            this.companyIDField = value;
        }
    }
    
    /// <remarks/>
    public int ResearchContributorStatusID {
        get {
            return this.researchContributorStatusIDField;
        }
        set {
            this.researchContributorStatusIDField = value;
        }
    }
    
    /// <remarks/>
    public bool hasResearch {
        get {
            return this.hasResearchField;
        }
        set {
            this.hasResearchField = value;
        }
    }
    
    /// <remarks/>
    public bool hasEstimates {
        get {
            return this.hasEstimatesField;
        }
        set {
            this.hasEstimatesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.capitaliq.com/CIQDotNet/ReferenceData")]
public partial class CalculationType : ReferenceDataInfo {
    
    private string referenceDataDescriptionField;
    
    private int financialGroupIdField;
    
    /// <remarks/>
    public string ReferenceDataDescription {
        get {
            return this.referenceDataDescriptionField;
        }
        set {
            this.referenceDataDescriptionField = value;
        }
    }
    
    /// <remarks/>
    public int FinancialGroupId {
        get {
            return this.financialGroupIdField;
        }
        set {
            this.financialGroupIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.capitaliq.com/CIQDotNet/ReferenceData")]
public partial class ReferenceDataWStringID : ReferenceDataInfo {
    
    private string referenceDataDescriptionField;
    
    /// <remarks/>
    public string ReferenceDataDescription {
        get {
            return this.referenceDataDescriptionField;
        }
        set {
            this.referenceDataDescriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.capitaliq.com/CIQDotNet/ReferenceData")]
public partial class CompanyRelTypeReferenceDataType : ReferenceDataInfo {
    
    private int companyRelTypeGroupField;
    
    /// <remarks/>
    public int CompanyRelTypeGroup {
        get {
            return this.companyRelTypeGroupField;
        }
        set {
            this.companyRelTypeGroupField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.capitaliq.com/CIQDotNet/ReferenceData")]
public partial class HoldingAdjustmentReferenceDataType : ReferenceDataInfo {
    
    private int isNegativeAdjustmentField;
    
    /// <remarks/>
    public int IsNegativeAdjustment {
        get {
            return this.isNegativeAdjustmentField;
        }
        set {
            this.isNegativeAdjustmentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.capitaliq.com/CIQDotNet/ReferenceData")]
public partial class ScaleReferenceDataType : ReferenceDataInfo {
    
    private decimal factorField;
    
    /// <remarks/>
    public decimal Factor {
        get {
            return this.factorField;
        }
        set {
            this.factorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.capitaliq.com/CIQDotNet/ReferenceData")]
public partial class StateReferenceDataType : ReferenceDataInfo {
    
    private int countryIDField;
    
    private string abbreviationField;
    
    /// <remarks/>
    public int CountryID {
        get {
            return this.countryIDField;
        }
        set {
            this.countryIDField = value;
        }
    }
    
    /// <remarks/>
    public string Abbreviation {
        get {
            return this.abbreviationField;
        }
        set {
            this.abbreviationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.capitaliq.com/CIQDotNet/ReferenceData")]
public partial class AnalystReferenceDataType : ReferenceDataInfo {
    
    private int researchContributorIdField;
    
    private string firstNameField;
    
    private string lastNameField;
    
    private string middleNameField;
    
    private int personIDField;
    
    private bool currentProFlagField;
    
    /// <remarks/>
    public int ResearchContributorId {
        get {
            return this.researchContributorIdField;
        }
        set {
            this.researchContributorIdField = value;
        }
    }
    
    /// <remarks/>
    public string FirstName {
        get {
            return this.firstNameField;
        }
        set {
            this.firstNameField = value;
        }
    }
    
    /// <remarks/>
    public string LastName {
        get {
            return this.lastNameField;
        }
        set {
            this.lastNameField = value;
        }
    }
    
    /// <remarks/>
    public string MiddleName {
        get {
            return this.middleNameField;
        }
        set {
            this.middleNameField = value;
        }
    }
    
    /// <remarks/>
    public int PersonID {
        get {
            return this.personIDField;
        }
        set {
            this.personIDField = value;
        }
    }
    
    /// <remarks/>
    public bool CurrentProFlag {
        get {
            return this.currentProFlagField;
        }
        set {
            this.currentProFlagField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.capitaliq.com/CIQDotNet/ReferenceData")]
public partial class RecommendationReferenceDataType : ReferenceDataInfo {
    
    private int contributorCompanyIDField;
    
    private decimal standardizedValueField;
    
    /// <remarks/>
    public int ContributorCompanyID {
        get {
            return this.contributorCompanyIDField;
        }
        set {
            this.contributorCompanyIDField = value;
        }
    }
    
    /// <remarks/>
    public decimal StandardizedValue {
        get {
            return this.standardizedValueField;
        }
        set {
            this.standardizedValueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void GetReferenceDataInfoCompletedEventHandler(object sender, GetReferenceDataInfoCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetReferenceDataInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetReferenceDataInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public ReferenceDataInfo[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((ReferenceDataInfo[])(this.results[0]));
        }
    }
}
