//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.42.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="GetCompetitorsSoap", Namespace="http://www.capitaliq.com/CIQDotNet/BusinessRel")]
public partial class GetCompetitors : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback GetCompetitorsInfoOperationCompleted;
    
    /// <remarks/>
    public GetCompetitors() {
        this.Url = "https://api.capitaliq.com/ciqdotnet/api/current/GetCompetitors.asmx";
    }
    
    /// <remarks/>
    public event GetCompetitorsInfoCompletedEventHandler GetCompetitorsInfoCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.capitaliq.com/CIQDotNet/BusinessRel/GetCompetitorsInfo", RequestNamespace="http://www.capitaliq.com/CIQDotNet/BusinessRel", ResponseNamespace="http://www.capitaliq.com/CIQDotNet/BusinessRel", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public CompetitorInfo[] GetCompetitorsInfo(int companyId, bool includeSubsidiariesFlag, int businessRelationshipSourceTypeId) {
        object[] results = this.Invoke("GetCompetitorsInfo", new object[] {
                    companyId,
                    includeSubsidiariesFlag,
                    businessRelationshipSourceTypeId});
        return ((CompetitorInfo[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetCompetitorsInfo(int companyId, bool includeSubsidiariesFlag, int businessRelationshipSourceTypeId, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetCompetitorsInfo", new object[] {
                    companyId,
                    includeSubsidiariesFlag,
                    businessRelationshipSourceTypeId}, callback, asyncState);
    }
    
    /// <remarks/>
    public CompetitorInfo[] EndGetCompetitorsInfo(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((CompetitorInfo[])(results[0]));
    }
    
    /// <remarks/>
    public void GetCompetitorsInfoAsync(int companyId, bool includeSubsidiariesFlag, int businessRelationshipSourceTypeId) {
        this.GetCompetitorsInfoAsync(companyId, includeSubsidiariesFlag, businessRelationshipSourceTypeId, null);
    }
    
    /// <remarks/>
    public void GetCompetitorsInfoAsync(int companyId, bool includeSubsidiariesFlag, int businessRelationshipSourceTypeId, object userState) {
        if ((this.GetCompetitorsInfoOperationCompleted == null)) {
            this.GetCompetitorsInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCompetitorsInfoOperationCompleted);
        }
        this.InvokeAsync("GetCompetitorsInfo", new object[] {
                    companyId,
                    includeSubsidiariesFlag,
                    businessRelationshipSourceTypeId}, this.GetCompetitorsInfoOperationCompleted, userState);
    }
    
    private void OnGetCompetitorsInfoOperationCompleted(object arg) {
        if ((this.GetCompetitorsInfoCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetCompetitorsInfoCompleted(this, new GetCompetitorsInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.capitaliq.com/CIQDotNet/BusinessRel")]
public partial class CompetitorInfo {
    
    private int companyIdField;
    
    private string companyNameField;
    
    private int competitorCompanyIdField;
    
    private string competitorCompanyNameField;
    
    private int businessRelationshipSourceTypeIdField;
    
    /// <remarks/>
    public int CompanyId {
        get {
            return this.companyIdField;
        }
        set {
            this.companyIdField = value;
        }
    }
    
    /// <remarks/>
    public string CompanyName {
        get {
            return this.companyNameField;
        }
        set {
            this.companyNameField = value;
        }
    }
    
    /// <remarks/>
    public int CompetitorCompanyId {
        get {
            return this.competitorCompanyIdField;
        }
        set {
            this.competitorCompanyIdField = value;
        }
    }
    
    /// <remarks/>
    public string CompetitorCompanyName {
        get {
            return this.competitorCompanyNameField;
        }
        set {
            this.competitorCompanyNameField = value;
        }
    }
    
    /// <remarks/>
    public int BusinessRelationshipSourceTypeId {
        get {
            return this.businessRelationshipSourceTypeIdField;
        }
        set {
            this.businessRelationshipSourceTypeIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void GetCompetitorsInfoCompletedEventHandler(object sender, GetCompetitorsInfoCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetCompetitorsInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetCompetitorsInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public CompetitorInfo[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((CompetitorInfo[])(this.results[0]));
        }
    }
}
