//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.42.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="ProfessionalsSoap", Namespace="http://www.capitaliq.com/CIQDotNet/Company/Professionals")]
public partial class Professionals : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback GetProfessionalsSummaryOperationCompleted;
    
    /// <remarks/>
    public Professionals() {
        this.Url = "https://api.capitaliq.com/ciqdotnet/api/current/Professionals.asmx";
    }
    
    /// <remarks/>
    public event GetProfessionalsSummaryCompletedEventHandler GetProfessionalsSummaryCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.capitaliq.com/CIQDotNet/Company/Professionals/GetProfessionalsSummary", RequestNamespace="http://www.capitaliq.com/CIQDotNet/Company/Professionals", ResponseNamespace="http://www.capitaliq.com/CIQDotNet/Company/Professionals", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public Professional[] GetProfessionalsSummary(int[] companyId, int professionalListFilter, int professionalStatusFilter, int[] professionalFunctionId) {
        object[] results = this.Invoke("GetProfessionalsSummary", new object[] {
                    companyId,
                    professionalListFilter,
                    professionalStatusFilter,
                    professionalFunctionId});
        return ((Professional[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetProfessionalsSummary(int[] companyId, int professionalListFilter, int professionalStatusFilter, int[] professionalFunctionId, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetProfessionalsSummary", new object[] {
                    companyId,
                    professionalListFilter,
                    professionalStatusFilter,
                    professionalFunctionId}, callback, asyncState);
    }
    
    /// <remarks/>
    public Professional[] EndGetProfessionalsSummary(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((Professional[])(results[0]));
    }
    
    /// <remarks/>
    public void GetProfessionalsSummaryAsync(int[] companyId, int professionalListFilter, int professionalStatusFilter, int[] professionalFunctionId) {
        this.GetProfessionalsSummaryAsync(companyId, professionalListFilter, professionalStatusFilter, professionalFunctionId, null);
    }
    
    /// <remarks/>
    public void GetProfessionalsSummaryAsync(int[] companyId, int professionalListFilter, int professionalStatusFilter, int[] professionalFunctionId, object userState) {
        if ((this.GetProfessionalsSummaryOperationCompleted == null)) {
            this.GetProfessionalsSummaryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProfessionalsSummaryOperationCompleted);
        }
        this.InvokeAsync("GetProfessionalsSummary", new object[] {
                    companyId,
                    professionalListFilter,
                    professionalStatusFilter,
                    professionalFunctionId}, this.GetProfessionalsSummaryOperationCompleted, userState);
    }
    
    private void OnGetProfessionalsSummaryOperationCompleted(object arg) {
        if ((this.GetProfessionalsSummaryCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetProfessionalsSummaryCompleted(this, new GetProfessionalsSummaryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.capitaliq.com/CIQDotNet/Company/Professionals")]
public partial class Professional : ProfessionalBase {
    
    private int personIdField;
    
    private string prefixField;
    
    private string salutationField;
    
    private string firstNameField;
    
    private string middleNameField;
    
    private string lastNameField;
    
    private string suffixField;
    
    private System.Nullable<int> yearBornField;
    
    private string personBiographyField;
    
    private string emailAddressField;
    
    private bool deceasedFlagField;
    
    private string titleField;
    
    private System.Nullable<int> proRankField;
    
    private System.Nullable<int> boardRankField;
    
    private ProFunctionInfo[] professionalFunctionsField;
    
    private ProfessionalBase[] otherAffiliationsField;
    
    /// <remarks/>
    public int PersonId {
        get {
            return this.personIdField;
        }
        set {
            this.personIdField = value;
        }
    }
    
    /// <remarks/>
    public string Prefix {
        get {
            return this.prefixField;
        }
        set {
            this.prefixField = value;
        }
    }
    
    /// <remarks/>
    public string Salutation {
        get {
            return this.salutationField;
        }
        set {
            this.salutationField = value;
        }
    }
    
    /// <remarks/>
    public string FirstName {
        get {
            return this.firstNameField;
        }
        set {
            this.firstNameField = value;
        }
    }
    
    /// <remarks/>
    public string MiddleName {
        get {
            return this.middleNameField;
        }
        set {
            this.middleNameField = value;
        }
    }
    
    /// <remarks/>
    public string LastName {
        get {
            return this.lastNameField;
        }
        set {
            this.lastNameField = value;
        }
    }
    
    /// <remarks/>
    public string Suffix {
        get {
            return this.suffixField;
        }
        set {
            this.suffixField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> YearBorn {
        get {
            return this.yearBornField;
        }
        set {
            this.yearBornField = value;
        }
    }
    
    /// <remarks/>
    public string PersonBiography {
        get {
            return this.personBiographyField;
        }
        set {
            this.personBiographyField = value;
        }
    }
    
    /// <remarks/>
    public string EmailAddress {
        get {
            return this.emailAddressField;
        }
        set {
            this.emailAddressField = value;
        }
    }
    
    /// <remarks/>
    public bool DeceasedFlag {
        get {
            return this.deceasedFlagField;
        }
        set {
            this.deceasedFlagField = value;
        }
    }
    
    /// <remarks/>
    public string Title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> ProRank {
        get {
            return this.proRankField;
        }
        set {
            this.proRankField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> BoardRank {
        get {
            return this.boardRankField;
        }
        set {
            this.boardRankField = value;
        }
    }
    
    /// <remarks/>
    public ProFunctionInfo[] ProfessionalFunctions {
        get {
            return this.professionalFunctionsField;
        }
        set {
            this.professionalFunctionsField = value;
        }
    }
    
    /// <remarks/>
    public ProfessionalBase[] OtherAffiliations {
        get {
            return this.otherAffiliationsField;
        }
        set {
            this.otherAffiliationsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.capitaliq.com/CIQDotNet/Company/Professionals")]
public partial class ProFunctionInfo {
    
    private int profunctionIdField;
    
    private string profunctionNameField;
    
    private string profunctionStartDateUTCField;
    
    private string profunctionEndDateUTCField;
    
    private bool currentFlagField;
    
    /// <remarks/>
    public int ProfunctionId {
        get {
            return this.profunctionIdField;
        }
        set {
            this.profunctionIdField = value;
        }
    }
    
    /// <remarks/>
    public string ProfunctionName {
        get {
            return this.profunctionNameField;
        }
        set {
            this.profunctionNameField = value;
        }
    }
    
    /// <remarks/>
    public string ProfunctionStartDateUTC {
        get {
            return this.profunctionStartDateUTCField;
        }
        set {
            this.profunctionStartDateUTCField = value;
        }
    }
    
    /// <remarks/>
    public string ProfunctionEndDateUTC {
        get {
            return this.profunctionEndDateUTCField;
        }
        set {
            this.profunctionEndDateUTCField = value;
        }
    }
    
    /// <remarks/>
    public bool CurrentFlag {
        get {
            return this.currentFlagField;
        }
        set {
            this.currentFlagField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(Professional))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.capitaliq.com/CIQDotNet/Company/Professionals")]
public partial class ProfessionalBase {
    
    private int professionalIdField;
    
    private int companyIdField;
    
    private string companyNameField;
    
    private int boardStatusIdField;
    
    private int professionalStatusIdField;
    
    private bool alumniFlagField;
    
    /// <remarks/>
    public int ProfessionalId {
        get {
            return this.professionalIdField;
        }
        set {
            this.professionalIdField = value;
        }
    }
    
    /// <remarks/>
    public int CompanyId {
        get {
            return this.companyIdField;
        }
        set {
            this.companyIdField = value;
        }
    }
    
    /// <remarks/>
    public string CompanyName {
        get {
            return this.companyNameField;
        }
        set {
            this.companyNameField = value;
        }
    }
    
    /// <remarks/>
    public int BoardStatusId {
        get {
            return this.boardStatusIdField;
        }
        set {
            this.boardStatusIdField = value;
        }
    }
    
    /// <remarks/>
    public int ProfessionalStatusId {
        get {
            return this.professionalStatusIdField;
        }
        set {
            this.professionalStatusIdField = value;
        }
    }
    
    /// <remarks/>
    public bool AlumniFlag {
        get {
            return this.alumniFlagField;
        }
        set {
            this.alumniFlagField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void GetProfessionalsSummaryCompletedEventHandler(object sender, GetProfessionalsSummaryCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetProfessionalsSummaryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetProfessionalsSummaryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public Professional[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((Professional[])(this.results[0]));
        }
    }
}
