//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4016
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="FinancialSummarySoap", Namespace="https://www.capitaliq.com/CIQDotNet/Financials/FinancialData")]
public partial class FinancialSummary : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback GetFinancialsOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetFinancialsUpdateDateOperationCompleted;
    
    /// <remarks/>
    public FinancialSummary() {
        this.Url = "https://api.capitaliq.com/CIQDOTNET/api/Current/FinancialSummary.asmx";
    }
    
    /// <remarks/>
    public event GetFinancialsCompletedEventHandler GetFinancialsCompleted;
    
    /// <remarks/>
    public event GetFinancialsUpdateDateCompletedEventHandler GetFinancialsUpdateDateCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.capitaliq.com/CIQDotNet/Financials/FinancialData/GetFinancials", RequestNamespace="https://www.capitaliq.com/CIQDotNet/Financials/FinancialData", ResponseNamespace="https://www.capitaliq.com/CIQDotNet/Financials/FinancialData", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public CompanyFinancials[] GetFinancials(int CompanyId, int[] FinancialGroupId, int PeriodTypeId, int TemplateTypeId, int RestatementTypeId, System.DateTime StartPeriodDate, System.DateTime EndPeriodDate, int CurrencyId, int CurrencyConversionMethod, int financialDataSetId) {
        object[] results = this.Invoke("GetFinancials", new object[] {
                    CompanyId,
                    FinancialGroupId,
                    PeriodTypeId,
                    TemplateTypeId,
                    RestatementTypeId,
                    StartPeriodDate,
                    EndPeriodDate,
                    CurrencyId,
                    CurrencyConversionMethod,
                    financialDataSetId});
        return ((CompanyFinancials[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetFinancials(int CompanyId, int[] FinancialGroupId, int PeriodTypeId, int TemplateTypeId, int RestatementTypeId, System.DateTime StartPeriodDate, System.DateTime EndPeriodDate, int CurrencyId, int CurrencyConversionMethod, int financialDataSetId, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetFinancials", new object[] {
                    CompanyId,
                    FinancialGroupId,
                    PeriodTypeId,
                    TemplateTypeId,
                    RestatementTypeId,
                    StartPeriodDate,
                    EndPeriodDate,
                    CurrencyId,
                    CurrencyConversionMethod,
                    financialDataSetId}, callback, asyncState);
    }
    
    /// <remarks/>
    public CompanyFinancials[] EndGetFinancials(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((CompanyFinancials[])(results[0]));
    }
    
    /// <remarks/>
    public void GetFinancialsAsync(int CompanyId, int[] FinancialGroupId, int PeriodTypeId, int TemplateTypeId, int RestatementTypeId, System.DateTime StartPeriodDate, System.DateTime EndPeriodDate, int CurrencyId, int CurrencyConversionMethod, int financialDataSetId) {
        this.GetFinancialsAsync(CompanyId, FinancialGroupId, PeriodTypeId, TemplateTypeId, RestatementTypeId, StartPeriodDate, EndPeriodDate, CurrencyId, CurrencyConversionMethod, financialDataSetId, null);
    }
    
    /// <remarks/>
    public void GetFinancialsAsync(int CompanyId, int[] FinancialGroupId, int PeriodTypeId, int TemplateTypeId, int RestatementTypeId, System.DateTime StartPeriodDate, System.DateTime EndPeriodDate, int CurrencyId, int CurrencyConversionMethod, int financialDataSetId, object userState) {
        if ((this.GetFinancialsOperationCompleted == null)) {
            this.GetFinancialsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFinancialsOperationCompleted);
        }
        this.InvokeAsync("GetFinancials", new object[] {
                    CompanyId,
                    FinancialGroupId,
                    PeriodTypeId,
                    TemplateTypeId,
                    RestatementTypeId,
                    StartPeriodDate,
                    EndPeriodDate,
                    CurrencyId,
                    CurrencyConversionMethod,
                    financialDataSetId}, this.GetFinancialsOperationCompleted, userState);
    }
    
    private void OnGetFinancialsOperationCompleted(object arg) {
        if ((this.GetFinancialsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetFinancialsCompleted(this, new GetFinancialsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.capitaliq.com/CIQDotNet/Financials/FinancialData/GetFinancialsUpdateD" +
        "ate", RequestNamespace="https://www.capitaliq.com/CIQDotNet/Financials/FinancialData", ResponseNamespace="https://www.capitaliq.com/CIQDotNet/Financials/FinancialData", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public FinancialUpdateInfo[] GetFinancialsUpdateDate(int[] CompanyId) {
        object[] results = this.Invoke("GetFinancialsUpdateDate", new object[] {
                    CompanyId});
        return ((FinancialUpdateInfo[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetFinancialsUpdateDate(int[] CompanyId, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetFinancialsUpdateDate", new object[] {
                    CompanyId}, callback, asyncState);
    }
    
    /// <remarks/>
    public FinancialUpdateInfo[] EndGetFinancialsUpdateDate(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((FinancialUpdateInfo[])(results[0]));
    }
    
    /// <remarks/>
    public void GetFinancialsUpdateDateAsync(int[] CompanyId) {
        this.GetFinancialsUpdateDateAsync(CompanyId, null);
    }
    
    /// <remarks/>
    public void GetFinancialsUpdateDateAsync(int[] CompanyId, object userState) {
        if ((this.GetFinancialsUpdateDateOperationCompleted == null)) {
            this.GetFinancialsUpdateDateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFinancialsUpdateDateOperationCompleted);
        }
        this.InvokeAsync("GetFinancialsUpdateDate", new object[] {
                    CompanyId}, this.GetFinancialsUpdateDateOperationCompleted, userState);
    }
    
    private void OnGetFinancialsUpdateDateOperationCompleted(object arg) {
        if ((this.GetFinancialsUpdateDateCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetFinancialsUpdateDateCompleted(this, new GetFinancialsUpdateDateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.capitaliq.com/CIQDotNet/Financials/FinancialData")]
public partial class CompanyFinancials {
    
    private int companyIdField;
    
    private int financialGroupIdField;
    
    private int templateTypeIdField;
    
    private FinancialInstanceInfo[] financialInstanceInfoListField;
    
    /// <remarks/>
    public int CompanyId {
        get {
            return this.companyIdField;
        }
        set {
            this.companyIdField = value;
        }
    }
    
    /// <remarks/>
    public int FinancialGroupId {
        get {
            return this.financialGroupIdField;
        }
        set {
            this.financialGroupIdField = value;
        }
    }
    
    /// <remarks/>
    public int TemplateTypeId {
        get {
            return this.templateTypeIdField;
        }
        set {
            this.templateTypeIdField = value;
        }
    }
    
    /// <remarks/>
    public FinancialInstanceInfo[] FinancialInstanceInfoList {
        get {
            return this.financialInstanceInfoListField;
        }
        set {
            this.financialInstanceInfoListField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.capitaliq.com/CIQDotNet/Financials/FinancialData")]
public partial class FinancialInstanceInfo {
    
    private string financialInstanceIdField;
    
    private int periodTypeIdField;
    
    private int calendarYearField;
    
    private int calendarQuarterField;
    
    private short instanceTypeIdField;
    
    private short currencyConversionMethodField;
    
    private int currencyIdField;
    
    private int reportedCurrencyIdField;
    
    private int fiscalYearField;
    
    private short fiscalQuarterField;
    
    private System.DateTime pEODateField;
    
    private System.DateTime filingDateField;
    
    private int financialDataSetIdField;
    
    private FinancialDataPoint[] dataItemListField;
    
    /// <remarks/>
    public string FinancialInstanceId {
        get {
            return this.financialInstanceIdField;
        }
        set {
            this.financialInstanceIdField = value;
        }
    }
    
    /// <remarks/>
    public int PeriodTypeId {
        get {
            return this.periodTypeIdField;
        }
        set {
            this.periodTypeIdField = value;
        }
    }
    
    /// <remarks/>
    public int CalendarYear {
        get {
            return this.calendarYearField;
        }
        set {
            this.calendarYearField = value;
        }
    }
    
    /// <remarks/>
    public int CalendarQuarter {
        get {
            return this.calendarQuarterField;
        }
        set {
            this.calendarQuarterField = value;
        }
    }
    
    /// <remarks/>
    public short InstanceTypeId {
        get {
            return this.instanceTypeIdField;
        }
        set {
            this.instanceTypeIdField = value;
        }
    }
    
    /// <remarks/>
    public short CurrencyConversionMethod {
        get {
            return this.currencyConversionMethodField;
        }
        set {
            this.currencyConversionMethodField = value;
        }
    }
    
    /// <remarks/>
    public int CurrencyId {
        get {
            return this.currencyIdField;
        }
        set {
            this.currencyIdField = value;
        }
    }
    
    /// <remarks/>
    public int ReportedCurrencyId {
        get {
            return this.reportedCurrencyIdField;
        }
        set {
            this.reportedCurrencyIdField = value;
        }
    }
    
    /// <remarks/>
    public int FiscalYear {
        get {
            return this.fiscalYearField;
        }
        set {
            this.fiscalYearField = value;
        }
    }
    
    /// <remarks/>
    public short FiscalQuarter {
        get {
            return this.fiscalQuarterField;
        }
        set {
            this.fiscalQuarterField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime PEODate {
        get {
            return this.pEODateField;
        }
        set {
            this.pEODateField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime FilingDate {
        get {
            return this.filingDateField;
        }
        set {
            this.filingDateField = value;
        }
    }
    
    /// <remarks/>
    public int FinancialDataSetId {
        get {
            return this.financialDataSetIdField;
        }
        set {
            this.financialDataSetIdField = value;
        }
    }
    
    /// <remarks/>
    public FinancialDataPoint[] DataItemList {
        get {
            return this.dataItemListField;
        }
        set {
            this.dataItemListField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.capitaliq.com/CIQDotNet/Financials/FinancialData")]
public partial class FinancialDataPoint {
    
    private string dataItemValueField;
    
    private System.Nullable<short> scaleIdField;
    
    private short unitTypeIdField;
    
    private int dataItemIdField;
    
    private bool auditableFlagField;
    
    private bool subtotalField;
    
    private int orderField;
    
    private int financialDataSetIdField;
    
    /// <remarks/>
    public string DataItemValue {
        get {
            return this.dataItemValueField;
        }
        set {
            this.dataItemValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<short> ScaleId {
        get {
            return this.scaleIdField;
        }
        set {
            this.scaleIdField = value;
        }
    }
    
    /// <remarks/>
    public short UnitTypeId {
        get {
            return this.unitTypeIdField;
        }
        set {
            this.unitTypeIdField = value;
        }
    }
    
    /// <remarks/>
    public int DataItemId {
        get {
            return this.dataItemIdField;
        }
        set {
            this.dataItemIdField = value;
        }
    }
    
    /// <remarks/>
    public bool AuditableFlag {
        get {
            return this.auditableFlagField;
        }
        set {
            this.auditableFlagField = value;
        }
    }
    
    /// <remarks/>
    public bool Subtotal {
        get {
            return this.subtotalField;
        }
        set {
            this.subtotalField = value;
        }
    }
    
    /// <remarks/>
    public int Order {
        get {
            return this.orderField;
        }
        set {
            this.orderField = value;
        }
    }
    
    /// <remarks/>
    public int FinancialDataSetId {
        get {
            return this.financialDataSetIdField;
        }
        set {
            this.financialDataSetIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.capitaliq.com/CIQDotNet/Financials/FinancialData")]
public partial class FinancialUpdateInfo {
    
    private int companyIdField;
    
    private string companyNameField;
    
    private System.DateTime lastUpdatedDateField;
    
    /// <remarks/>
    public int CompanyId {
        get {
            return this.companyIdField;
        }
        set {
            this.companyIdField = value;
        }
    }
    
    /// <remarks/>
    public string CompanyName {
        get {
            return this.companyNameField;
        }
        set {
            this.companyNameField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime LastUpdatedDate {
        get {
            return this.lastUpdatedDateField;
        }
        set {
            this.lastUpdatedDateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void GetFinancialsCompletedEventHandler(object sender, GetFinancialsCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetFinancialsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetFinancialsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public CompanyFinancials[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((CompanyFinancials[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void GetFinancialsUpdateDateCompletedEventHandler(object sender, GetFinancialsUpdateDateCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetFinancialsUpdateDateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetFinancialsUpdateDateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public FinancialUpdateInfo[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((FinancialUpdateInfo[])(this.results[0]));
        }
    }
}
