//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.42.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="GetCompanyInfoSoap", Namespace="http://www.capitaliq.com/CiqDotNet/Company/GetCompanyInfo")]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseAddress))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(CompanyBase))]
public partial class GetCompanyInfo : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback CallGetCompanyInfoOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetCompanyDetailOperationCompleted;
    
    /// <remarks/>
    public GetCompanyInfo() {
        this.Url = "https://api.capitaliq.com/ciqdotnet/api/current/GetCompanyInfo.asmx";
    }
    
    /// <remarks/>
    public event CallGetCompanyInfoCompletedEventHandler CallGetCompanyInfoCompleted;
    
    /// <remarks/>
    public event GetCompanyDetailCompletedEventHandler GetCompanyDetailCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.capitaliq.com/CiqDotNet/Company/GetCompanyInfo/GetCompanyInfo", RequestElementName="GetCompanyInfo", RequestNamespace="http://www.capitaliq.com/CiqDotNet/Company/GetCompanyInfo", ResponseElementName="GetCompanyInfoResponse", ResponseNamespace="http://www.capitaliq.com/CiqDotNet/Company/GetCompanyInfo", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlArrayAttribute("GetCompanyInfoResult")]
    public CompanySummary[] CallGetCompanyInfo(int[] companyId) {
        object[] results = this.Invoke("CallGetCompanyInfo", new object[] {
                    companyId});
        return ((CompanySummary[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginCallGetCompanyInfo(int[] companyId, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("CallGetCompanyInfo", new object[] {
                    companyId}, callback, asyncState);
    }
    
    /// <remarks/>
    public CompanySummary[] EndCallGetCompanyInfo(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((CompanySummary[])(results[0]));
    }
    
    /// <remarks/>
    public void CallGetCompanyInfoAsync(int[] companyId) {
        this.CallGetCompanyInfoAsync(companyId, null);
    }
    
    /// <remarks/>
    public void CallGetCompanyInfoAsync(int[] companyId, object userState) {
        if ((this.CallGetCompanyInfoOperationCompleted == null)) {
            this.CallGetCompanyInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCallGetCompanyInfoOperationCompleted);
        }
        this.InvokeAsync("CallGetCompanyInfo", new object[] {
                    companyId}, this.CallGetCompanyInfoOperationCompleted, userState);
    }
    
    private void OnCallGetCompanyInfoOperationCompleted(object arg) {
        if ((this.CallGetCompanyInfoCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.CallGetCompanyInfoCompleted(this, new CallGetCompanyInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.capitaliq.com/CiqDotNet/Company/GetCompanyInfo/GetCompanyDetail", RequestNamespace="http://www.capitaliq.com/CiqDotNet/Company/GetCompanyInfo", ResponseNamespace="http://www.capitaliq.com/CiqDotNet/Company/GetCompanyInfo", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public CompanyDetail[] GetCompanyDetail(int[] companyId) {
        object[] results = this.Invoke("GetCompanyDetail", new object[] {
                    companyId});
        return ((CompanyDetail[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetCompanyDetail(int[] companyId, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetCompanyDetail", new object[] {
                    companyId}, callback, asyncState);
    }
    
    /// <remarks/>
    public CompanyDetail[] EndGetCompanyDetail(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((CompanyDetail[])(results[0]));
    }
    
    /// <remarks/>
    public void GetCompanyDetailAsync(int[] companyId) {
        this.GetCompanyDetailAsync(companyId, null);
    }
    
    /// <remarks/>
    public void GetCompanyDetailAsync(int[] companyId, object userState) {
        if ((this.GetCompanyDetailOperationCompleted == null)) {
            this.GetCompanyDetailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCompanyDetailOperationCompleted);
        }
        this.InvokeAsync("GetCompanyDetail", new object[] {
                    companyId}, this.GetCompanyDetailOperationCompleted, userState);
    }
    
    private void OnGetCompanyDetailOperationCompleted(object arg) {
        if ((this.GetCompanyDetailCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetCompanyDetailCompleted(this, new GetCompanyDetailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(CompanyDetail))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.capitaliq.com/CiqDotNet/Company/GetCompanyInfo")]
public partial class CompanySummary : CompanyBase {
    
    private string webSiteURLField;
    
    private string businessDescriptionField;
    
    private string longBusinessDescriptionField;
    
    private System.Nullable<int> primaryTradingItemIdField;
    
    private System.Nullable<int> primaryExchangeIdField;
    
    private string primaryExchangeNameField;
    
    private string primaryExchangeSymbolField;
    
    private System.Nullable<int> simpleIndustryIdField;
    
    private string simpleIndustryNameField;
    
    private string sectorIdField;
    
    private string sectorNameField;
    
    private string industryGroupIdField;
    
    private string industryGroupNameField;
    
    private string industryIdField;
    
    private string industryNameField;
    
    private string subIndustryIdField;
    
    private string subIndustryNameField;
    
    private System.Nullable<int> ultimateParentCompanyIdField;
    
    private string ultimateParentCompanyNameField;
    
    private System.Nullable<int> yearFoundedField;
    
    private System.Nullable<int> numberOfEmployeesField;
    
    private bool hasSubsidiariesAndInvestmentsFlagField;
    
    private bool hasFinancialsFlagField;
    
    private System.Nullable<int> templateTypeIdField;
    
    private PrimaryCompanyAddress primaryAddressInfoField;
    
    /// <remarks/>
    public string WebSiteURL {
        get {
            return this.webSiteURLField;
        }
        set {
            this.webSiteURLField = value;
        }
    }
    
    /// <remarks/>
    public string BusinessDescription {
        get {
            return this.businessDescriptionField;
        }
        set {
            this.businessDescriptionField = value;
        }
    }
    
    /// <remarks/>
    public string LongBusinessDescription {
        get {
            return this.longBusinessDescriptionField;
        }
        set {
            this.longBusinessDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> PrimaryTradingItemId {
        get {
            return this.primaryTradingItemIdField;
        }
        set {
            this.primaryTradingItemIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> PrimaryExchangeId {
        get {
            return this.primaryExchangeIdField;
        }
        set {
            this.primaryExchangeIdField = value;
        }
    }
    
    /// <remarks/>
    public string PrimaryExchangeName {
        get {
            return this.primaryExchangeNameField;
        }
        set {
            this.primaryExchangeNameField = value;
        }
    }
    
    /// <remarks/>
    public string PrimaryExchangeSymbol {
        get {
            return this.primaryExchangeSymbolField;
        }
        set {
            this.primaryExchangeSymbolField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> SimpleIndustryId {
        get {
            return this.simpleIndustryIdField;
        }
        set {
            this.simpleIndustryIdField = value;
        }
    }
    
    /// <remarks/>
    public string SimpleIndustryName {
        get {
            return this.simpleIndustryNameField;
        }
        set {
            this.simpleIndustryNameField = value;
        }
    }
    
    /// <remarks/>
    public string SectorId {
        get {
            return this.sectorIdField;
        }
        set {
            this.sectorIdField = value;
        }
    }
    
    /// <remarks/>
    public string SectorName {
        get {
            return this.sectorNameField;
        }
        set {
            this.sectorNameField = value;
        }
    }
    
    /// <remarks/>
    public string IndustryGroupId {
        get {
            return this.industryGroupIdField;
        }
        set {
            this.industryGroupIdField = value;
        }
    }
    
    /// <remarks/>
    public string IndustryGroupName {
        get {
            return this.industryGroupNameField;
        }
        set {
            this.industryGroupNameField = value;
        }
    }
    
    /// <remarks/>
    public string IndustryId {
        get {
            return this.industryIdField;
        }
        set {
            this.industryIdField = value;
        }
    }
    
    /// <remarks/>
    public string IndustryName {
        get {
            return this.industryNameField;
        }
        set {
            this.industryNameField = value;
        }
    }
    
    /// <remarks/>
    public string SubIndustryId {
        get {
            return this.subIndustryIdField;
        }
        set {
            this.subIndustryIdField = value;
        }
    }
    
    /// <remarks/>
    public string SubIndustryName {
        get {
            return this.subIndustryNameField;
        }
        set {
            this.subIndustryNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> UltimateParentCompanyId {
        get {
            return this.ultimateParentCompanyIdField;
        }
        set {
            this.ultimateParentCompanyIdField = value;
        }
    }
    
    /// <remarks/>
    public string UltimateParentCompanyName {
        get {
            return this.ultimateParentCompanyNameField;
        }
        set {
            this.ultimateParentCompanyNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> YearFounded {
        get {
            return this.yearFoundedField;
        }
        set {
            this.yearFoundedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> NumberOfEmployees {
        get {
            return this.numberOfEmployeesField;
        }
        set {
            this.numberOfEmployeesField = value;
        }
    }
    
    /// <remarks/>
    public bool HasSubsidiariesAndInvestmentsFlag {
        get {
            return this.hasSubsidiariesAndInvestmentsFlagField;
        }
        set {
            this.hasSubsidiariesAndInvestmentsFlagField = value;
        }
    }
    
    /// <remarks/>
    public bool HasFinancialsFlag {
        get {
            return this.hasFinancialsFlagField;
        }
        set {
            this.hasFinancialsFlagField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> TemplateTypeId {
        get {
            return this.templateTypeIdField;
        }
        set {
            this.templateTypeIdField = value;
        }
    }
    
    /// <remarks/>
    public PrimaryCompanyAddress PrimaryAddressInfo {
        get {
            return this.primaryAddressInfoField;
        }
        set {
            this.primaryAddressInfoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.capitaliq.com/CiqDotNet/Company/GetCompanyInfo")]
public partial class PrimaryCompanyAddress : BaseAddress {
    
    private string streetAddress1Field;
    
    private string streetAddress2Field;
    
    private string streetAddress3Field;
    
    private string streetAddress4Field;
    
    private System.Nullable<int> stateIDField;
    
    private int countryIDField;
    
    private string stateNameField;
    
    private string countryNameField;
    
    private string stateAbbreviationField;
    
    /// <remarks/>
    public string StreetAddress1 {
        get {
            return this.streetAddress1Field;
        }
        set {
            this.streetAddress1Field = value;
        }
    }
    
    /// <remarks/>
    public string StreetAddress2 {
        get {
            return this.streetAddress2Field;
        }
        set {
            this.streetAddress2Field = value;
        }
    }
    
    /// <remarks/>
    public string StreetAddress3 {
        get {
            return this.streetAddress3Field;
        }
        set {
            this.streetAddress3Field = value;
        }
    }
    
    /// <remarks/>
    public string StreetAddress4 {
        get {
            return this.streetAddress4Field;
        }
        set {
            this.streetAddress4Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> StateID {
        get {
            return this.stateIDField;
        }
        set {
            this.stateIDField = value;
        }
    }
    
    /// <remarks/>
    public int CountryID {
        get {
            return this.countryIDField;
        }
        set {
            this.countryIDField = value;
        }
    }
    
    /// <remarks/>
    public string StateName {
        get {
            return this.stateNameField;
        }
        set {
            this.stateNameField = value;
        }
    }
    
    /// <remarks/>
    public string CountryName {
        get {
            return this.countryNameField;
        }
        set {
            this.countryNameField = value;
        }
    }
    
    /// <remarks/>
    public string StateAbbreviation {
        get {
            return this.stateAbbreviationField;
        }
        set {
            this.stateAbbreviationField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(PrimaryCompanyAddress))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.capitaliq.com/CiqDotNet/Company/GetCompanyInfo")]
public partial class BaseAddress {
    
    private int addressIDField;
    
    private string cityField;
    
    private string zipPostalCodeField;
    
    private string phoneField;
    
    private string faxField;
    
    /// <remarks/>
    public int AddressID {
        get {
            return this.addressIDField;
        }
        set {
            this.addressIDField = value;
        }
    }
    
    /// <remarks/>
    public string City {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    public string ZipPostalCode {
        get {
            return this.zipPostalCodeField;
        }
        set {
            this.zipPostalCodeField = value;
        }
    }
    
    /// <remarks/>
    public string Phone {
        get {
            return this.phoneField;
        }
        set {
            this.phoneField = value;
        }
    }
    
    /// <remarks/>
    public string Fax {
        get {
            return this.faxField;
        }
        set {
            this.faxField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.capitaliq.com/CiqDotNet/Company/GetCompanyInfo")]
public partial class TradingItem {
    
    private int tradingItemIDField;
    
    private string tickerSymbolField;
    
    private int exchangeIDField;
    
    private string exchangeSymbolField;
    
    private bool hasEstimatesFlagField;
    
    private System.Nullable<bool> activeFlagField;
    
    /// <remarks/>
    public int TradingItemID {
        get {
            return this.tradingItemIDField;
        }
        set {
            this.tradingItemIDField = value;
        }
    }
    
    /// <remarks/>
    public string TickerSymbol {
        get {
            return this.tickerSymbolField;
        }
        set {
            this.tickerSymbolField = value;
        }
    }
    
    /// <remarks/>
    public int ExchangeID {
        get {
            return this.exchangeIDField;
        }
        set {
            this.exchangeIDField = value;
        }
    }
    
    /// <remarks/>
    public string ExchangeSymbol {
        get {
            return this.exchangeSymbolField;
        }
        set {
            this.exchangeSymbolField = value;
        }
    }
    
    /// <remarks/>
    public bool HasEstimatesFlag {
        get {
            return this.hasEstimatesFlagField;
        }
        set {
            this.hasEstimatesFlagField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<bool> ActiveFlag {
        get {
            return this.activeFlagField;
        }
        set {
            this.activeFlagField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(CompanySummary))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(CompanyDetail))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.capitaliq.com/CiqDotNet/Company/GetCompanyInfo")]
public partial class CompanyBase {
    
    private int companyIdField;
    
    private string companyNameField;
    
    private int companyTypeIdField;
    
    private string companyTypeNameField;
    
    private int companyStatusTypeIdField;
    
    private string companyStatusTypeNameField;
    
    private string primaryTickerSymbolField;
    
    /// <remarks/>
    public int CompanyId {
        get {
            return this.companyIdField;
        }
        set {
            this.companyIdField = value;
        }
    }
    
    /// <remarks/>
    public string CompanyName {
        get {
            return this.companyNameField;
        }
        set {
            this.companyNameField = value;
        }
    }
    
    /// <remarks/>
    public int CompanyTypeId {
        get {
            return this.companyTypeIdField;
        }
        set {
            this.companyTypeIdField = value;
        }
    }
    
    /// <remarks/>
    public string CompanyTypeName {
        get {
            return this.companyTypeNameField;
        }
        set {
            this.companyTypeNameField = value;
        }
    }
    
    /// <remarks/>
    public int CompanyStatusTypeId {
        get {
            return this.companyStatusTypeIdField;
        }
        set {
            this.companyStatusTypeIdField = value;
        }
    }
    
    /// <remarks/>
    public string CompanyStatusTypeName {
        get {
            return this.companyStatusTypeNameField;
        }
        set {
            this.companyStatusTypeNameField = value;
        }
    }
    
    /// <remarks/>
    public string PrimaryTickerSymbol {
        get {
            return this.primaryTickerSymbolField;
        }
        set {
            this.primaryTickerSymbolField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.capitaliq.com/CiqDotNet/Company/GetCompanyInfo")]
public partial class CompanyDetail : CompanySummary {
    
    private TradingItem[] tradingItemsField;
    
    /// <remarks/>
    public TradingItem[] TradingItems {
        get {
            return this.tradingItemsField;
        }
        set {
            this.tradingItemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void CallGetCompanyInfoCompletedEventHandler(object sender, CallGetCompanyInfoCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CallGetCompanyInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal CallGetCompanyInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public CompanySummary[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((CompanySummary[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void GetCompanyDetailCompletedEventHandler(object sender, GetCompanyDetailCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetCompanyDetailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetCompanyDetailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public CompanyDetail[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((CompanyDetail[])(this.results[0]));
        }
    }
}
