//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplicationAPIWebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebService2
    {
        public int id { get; set; }
        public string Asset { get; set; }
        public string Business_Description { get; set; }
        public string Website { get; set; }
        public string Company_Type { get; set; }
        public string Stock_Symbol { get; set; }
        public Nullable<decimal> Market_Cap { get; set; }
        public string DUNS_Number { get; set; }
        public Nullable<int> NAICS_Code { get; set; }
        public string NAICS_Description { get; set; }
        public Nullable<int> SIC_Code { get; set; }
        public string SIC_Description { get; set; }
        public Nullable<decimal> Total_Revenue { get; set; }
        public Nullable<int> Year_Found { get; set; }
        public Nullable<double> Total_Employees { get; set; }
        public string HeadQuarters_Address { get; set; }
        public string Telephone_Number { get; set; }
        public string Key_Personnel { get; set; }
        public string Parent_Company { get; set; }
        public Nullable<bool> Past_or_Present_Insured { get; set; }
        public string Submission_Activity { get; set; }
        public string GURU { get; set; }
        public string FEIN_Number { get; set; }
        public string SubsidiaryList { get; set; }
        public string QuickMatchID { get; set; }
        public string QuickMatchName { get; set; }
        public string AddressSource { get; set; }
    }
}
