//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.42.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="GetDocumentDetailsServiceSoap", Namespace="http://capitaliq.com/ciqdotnet/filings/GetDocumentDetails")]
public partial class GetDocumentDetailsService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback GetDocumentDetailsOperationCompleted;
    
    /// <remarks/>
    public GetDocumentDetailsService() {
        this.Url = "https://api.capitaliq.com/ciqdotnet/api/1.0/GetDocumentDetails.asmx";
    }
    
    /// <remarks/>
    public event GetDocumentDetailsCompletedEventHandler GetDocumentDetailsCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://capitaliq.com/ciqdotnet/filings/GetDocumentDetails/GetDocumentDetails", RequestNamespace="http://capitaliq.com/ciqdotnet/filings/GetDocumentDetails", ResponseNamespace="http://capitaliq.com/ciqdotnet/filings/GetDocumentDetails", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public FilingsDocument GetDocumentDetails(string SupplierDocumentId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> VersionId, DocumentOutputType TargetFormat, string DataValue) {
        object[] results = this.Invoke("GetDocumentDetails", new object[] {
                    SupplierDocumentId,
                    VersionId,
                    TargetFormat,
                    DataValue});
        return ((FilingsDocument)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetDocumentDetails(string SupplierDocumentId, System.Nullable<int> VersionId, DocumentOutputType TargetFormat, string DataValue, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetDocumentDetails", new object[] {
                    SupplierDocumentId,
                    VersionId,
                    TargetFormat,
                    DataValue}, callback, asyncState);
    }
    
    /// <remarks/>
    public FilingsDocument EndGetDocumentDetails(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((FilingsDocument)(results[0]));
    }
    
    /// <remarks/>
    public void GetDocumentDetailsAsync(string SupplierDocumentId, System.Nullable<int> VersionId, DocumentOutputType TargetFormat, string DataValue) {
        this.GetDocumentDetailsAsync(SupplierDocumentId, VersionId, TargetFormat, DataValue, null);
    }
    
    /// <remarks/>
    public void GetDocumentDetailsAsync(string SupplierDocumentId, System.Nullable<int> VersionId, DocumentOutputType TargetFormat, string DataValue, object userState) {
        if ((this.GetDocumentDetailsOperationCompleted == null)) {
            this.GetDocumentDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDocumentDetailsOperationCompleted);
        }
        this.InvokeAsync("GetDocumentDetails", new object[] {
                    SupplierDocumentId,
                    VersionId,
                    TargetFormat,
                    DataValue}, this.GetDocumentDetailsOperationCompleted, userState);
    }
    
    private void OnGetDocumentDetailsOperationCompleted(object arg) {
        if ((this.GetDocumentDetailsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetDocumentDetailsCompleted(this, new GetDocumentDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://capitaliq.com/ciqdotnet/filings/GetDocumentDetails")]
public enum DocumentOutputType {
    
    /// <remarks/>
    html,
    
    /// <remarks/>
    xls,
    
    /// <remarks/>
    doc,
    
    /// <remarks/>
    pdf,
    
    /// <remarks/>
    raw,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://capitaliq.com/ciqdotnet/filings/GetDocumentDetails")]
public partial class FilingsDocument {
    
    private string supplierDocumentIdField;
    
    private int versionIdField;
    
    private string documentLocationField;
    
    private DataValueLink[] anchorListField;
    
    /// <remarks/>
    public string SupplierDocumentId {
        get {
            return this.supplierDocumentIdField;
        }
        set {
            this.supplierDocumentIdField = value;
        }
    }
    
    /// <remarks/>
    public int VersionId {
        get {
            return this.versionIdField;
        }
        set {
            this.versionIdField = value;
        }
    }
    
    /// <remarks/>
    public string DocumentLocation {
        get {
            return this.documentLocationField;
        }
        set {
            this.documentLocationField = value;
        }
    }
    
    /// <remarks/>
    public DataValueLink[] AnchorList {
        get {
            return this.anchorListField;
        }
        set {
            this.anchorListField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://capitaliq.com/ciqdotnet/filings/GetDocumentDetails")]
public partial class DataValueLink {
    
    private string dataValueField;
    
    private string[] anchorNameListField;
    
    /// <remarks/>
    public string DataValue {
        get {
            return this.dataValueField;
        }
        set {
            this.dataValueField = value;
        }
    }
    
    /// <remarks/>
    public string[] AnchorNameList {
        get {
            return this.anchorNameListField;
        }
        set {
            this.anchorNameListField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void GetDocumentDetailsCompletedEventHandler(object sender, GetDocumentDetailsCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetDocumentDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetDocumentDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public FilingsDocument Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((FilingsDocument)(this.results[0]));
        }
    }
}
