//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.42.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="ProfessionalsDetailSoap", Namespace="http://www.capitaliq.com/CIQDotNet/Company/ProfessionalsDetail")]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ProfessionalBase))]
public partial class ProfessionalsDetail : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback GetProfessionalsDetailOperationCompleted;
    
    /// <remarks/>
    public ProfessionalsDetail() {
        this.Url = "https://api.capitaliq.com/ciqdotnet/api/current/ProfessionalsDetail.asmx";
    }
    
    /// <remarks/>
    public event GetProfessionalsDetailCompletedEventHandler GetProfessionalsDetailCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.capitaliq.com/CIQDotNet/Company/ProfessionalsDetail/GetProfessionalsDe" +
        "tail", RequestNamespace="http://www.capitaliq.com/CIQDotNet/Company/ProfessionalsDetail", ResponseNamespace="http://www.capitaliq.com/CIQDotNet/Company/ProfessionalsDetail", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public Person[] GetProfessionalsDetail(int[] personId, int[] professionalId) {
        object[] results = this.Invoke("GetProfessionalsDetail", new object[] {
                    personId,
                    professionalId});
        return ((Person[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetProfessionalsDetail(int[] personId, int[] professionalId, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetProfessionalsDetail", new object[] {
                    personId,
                    professionalId}, callback, asyncState);
    }
    
    /// <remarks/>
    public Person[] EndGetProfessionalsDetail(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((Person[])(results[0]));
    }
    
    /// <remarks/>
    public void GetProfessionalsDetailAsync(int[] personId, int[] professionalId) {
        this.GetProfessionalsDetailAsync(personId, professionalId, null);
    }
    
    /// <remarks/>
    public void GetProfessionalsDetailAsync(int[] personId, int[] professionalId, object userState) {
        if ((this.GetProfessionalsDetailOperationCompleted == null)) {
            this.GetProfessionalsDetailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProfessionalsDetailOperationCompleted);
        }
        this.InvokeAsync("GetProfessionalsDetail", new object[] {
                    personId,
                    professionalId}, this.GetProfessionalsDetailOperationCompleted, userState);
    }
    
    private void OnGetProfessionalsDetailOperationCompleted(object arg) {
        if ((this.GetProfessionalsDetailCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetProfessionalsDetailCompleted(this, new GetProfessionalsDetailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.capitaliq.com/CIQDotNet/Company/ProfessionalsDetail")]
public partial class Person {
    
    private int personIdField;
    
    private string prefixField;
    
    private string salutationField;
    
    private string firstNameField;
    
    private string middleNameField;
    
    private string lastNameField;
    
    private string suffixField;
    
    private string yearBornField;
    
    private string personBiographyField;
    
    private string emailAddressField;
    
    private bool deceasedFlagField;
    
    private ProfessionalDetail[] professionalDetailsField;
    
    /// <remarks/>
    public int PersonId {
        get {
            return this.personIdField;
        }
        set {
            this.personIdField = value;
        }
    }
    
    /// <remarks/>
    public string Prefix {
        get {
            return this.prefixField;
        }
        set {
            this.prefixField = value;
        }
    }
    
    /// <remarks/>
    public string Salutation {
        get {
            return this.salutationField;
        }
        set {
            this.salutationField = value;
        }
    }
    
    /// <remarks/>
    public string FirstName {
        get {
            return this.firstNameField;
        }
        set {
            this.firstNameField = value;
        }
    }
    
    /// <remarks/>
    public string MiddleName {
        get {
            return this.middleNameField;
        }
        set {
            this.middleNameField = value;
        }
    }
    
    /// <remarks/>
    public string LastName {
        get {
            return this.lastNameField;
        }
        set {
            this.lastNameField = value;
        }
    }
    
    /// <remarks/>
    public string Suffix {
        get {
            return this.suffixField;
        }
        set {
            this.suffixField = value;
        }
    }
    
    /// <remarks/>
    public string YearBorn {
        get {
            return this.yearBornField;
        }
        set {
            this.yearBornField = value;
        }
    }
    
    /// <remarks/>
    public string PersonBiography {
        get {
            return this.personBiographyField;
        }
        set {
            this.personBiographyField = value;
        }
    }
    
    /// <remarks/>
    public string EmailAddress {
        get {
            return this.emailAddressField;
        }
        set {
            this.emailAddressField = value;
        }
    }
    
    /// <remarks/>
    public bool DeceasedFlag {
        get {
            return this.deceasedFlagField;
        }
        set {
            this.deceasedFlagField = value;
        }
    }
    
    /// <remarks/>
    public ProfessionalDetail[] ProfessionalDetails {
        get {
            return this.professionalDetailsField;
        }
        set {
            this.professionalDetailsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.capitaliq.com/CIQDotNet/Company/ProfessionalsDetail")]
public partial class ProfessionalDetail : ProfessionalBase {
    
    private string titleField;
    
    private System.Nullable<int> proRankField;
    
    private System.Nullable<int> boardRankField;
    
    private string addressLine1Field;
    
    private string addressLine2Field;
    
    private string addressLine3Field;
    
    private string addressLine4Field;
    
    private string cityNameField;
    
    private System.Nullable<int> stateIdField;
    
    private string stateNameField;
    
    private string zipCodeField;
    
    private System.Nullable<int> countryIdField;
    
    private string countryNameField;
    
    private string mainfaxNumberField;
    
    private string mainPhoneNumberField;
    
    private ProFunctionInfo[] professionalFunctionsField;
    
    private Compensation[] compensationsField;
    
    /// <remarks/>
    public string Title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> ProRank {
        get {
            return this.proRankField;
        }
        set {
            this.proRankField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> BoardRank {
        get {
            return this.boardRankField;
        }
        set {
            this.boardRankField = value;
        }
    }
    
    /// <remarks/>
    public string AddressLine1 {
        get {
            return this.addressLine1Field;
        }
        set {
            this.addressLine1Field = value;
        }
    }
    
    /// <remarks/>
    public string AddressLine2 {
        get {
            return this.addressLine2Field;
        }
        set {
            this.addressLine2Field = value;
        }
    }
    
    /// <remarks/>
    public string AddressLine3 {
        get {
            return this.addressLine3Field;
        }
        set {
            this.addressLine3Field = value;
        }
    }
    
    /// <remarks/>
    public string AddressLine4 {
        get {
            return this.addressLine4Field;
        }
        set {
            this.addressLine4Field = value;
        }
    }
    
    /// <remarks/>
    public string CityName {
        get {
            return this.cityNameField;
        }
        set {
            this.cityNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> StateId {
        get {
            return this.stateIdField;
        }
        set {
            this.stateIdField = value;
        }
    }
    
    /// <remarks/>
    public string StateName {
        get {
            return this.stateNameField;
        }
        set {
            this.stateNameField = value;
        }
    }
    
    /// <remarks/>
    public string ZipCode {
        get {
            return this.zipCodeField;
        }
        set {
            this.zipCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> CountryId {
        get {
            return this.countryIdField;
        }
        set {
            this.countryIdField = value;
        }
    }
    
    /// <remarks/>
    public string CountryName {
        get {
            return this.countryNameField;
        }
        set {
            this.countryNameField = value;
        }
    }
    
    /// <remarks/>
    public string MainfaxNumber {
        get {
            return this.mainfaxNumberField;
        }
        set {
            this.mainfaxNumberField = value;
        }
    }
    
    /// <remarks/>
    public string MainPhoneNumber {
        get {
            return this.mainPhoneNumberField;
        }
        set {
            this.mainPhoneNumberField = value;
        }
    }
    
    /// <remarks/>
    public ProFunctionInfo[] ProfessionalFunctions {
        get {
            return this.professionalFunctionsField;
        }
        set {
            this.professionalFunctionsField = value;
        }
    }
    
    /// <remarks/>
    public Compensation[] Compensations {
        get {
            return this.compensationsField;
        }
        set {
            this.compensationsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.capitaliq.com/CIQDotNet/Company/ProfessionalsDetail")]
public partial class ProFunctionInfo {
    
    private int profunctionIdField;
    
    private string profunctionNameField;
    
    private string profunctionStartDateUTCField;
    
    private string profunctionEndDateUTCField;
    
    private bool currentFlagField;
    
    /// <remarks/>
    public int ProfunctionId {
        get {
            return this.profunctionIdField;
        }
        set {
            this.profunctionIdField = value;
        }
    }
    
    /// <remarks/>
    public string ProfunctionName {
        get {
            return this.profunctionNameField;
        }
        set {
            this.profunctionNameField = value;
        }
    }
    
    /// <remarks/>
    public string ProfunctionStartDateUTC {
        get {
            return this.profunctionStartDateUTCField;
        }
        set {
            this.profunctionStartDateUTCField = value;
        }
    }
    
    /// <remarks/>
    public string ProfunctionEndDateUTC {
        get {
            return this.profunctionEndDateUTCField;
        }
        set {
            this.profunctionEndDateUTCField = value;
        }
    }
    
    /// <remarks/>
    public bool CurrentFlag {
        get {
            return this.currentFlagField;
        }
        set {
            this.currentFlagField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.capitaliq.com/CIQDotNet/Company/ProfessionalsDetail")]
public partial class Compensation {
    
    private int currencyIdField;
    
    private string currencyNameField;
    
    private int compensationTypeIdField;
    
    private string compensationTypeNameField;
    
    private int compensationFiscalYearField;
    
    private System.DateTime compensationFilingDateField;
    
    private string compensationValueField;
    
    /// <remarks/>
    public int CurrencyId {
        get {
            return this.currencyIdField;
        }
        set {
            this.currencyIdField = value;
        }
    }
    
    /// <remarks/>
    public string CurrencyName {
        get {
            return this.currencyNameField;
        }
        set {
            this.currencyNameField = value;
        }
    }
    
    /// <remarks/>
    public int CompensationTypeId {
        get {
            return this.compensationTypeIdField;
        }
        set {
            this.compensationTypeIdField = value;
        }
    }
    
    /// <remarks/>
    public string CompensationTypeName {
        get {
            return this.compensationTypeNameField;
        }
        set {
            this.compensationTypeNameField = value;
        }
    }
    
    /// <remarks/>
    public int CompensationFiscalYear {
        get {
            return this.compensationFiscalYearField;
        }
        set {
            this.compensationFiscalYearField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime CompensationFilingDate {
        get {
            return this.compensationFilingDateField;
        }
        set {
            this.compensationFilingDateField = value;
        }
    }
    
    /// <remarks/>
    public string CompensationValue {
        get {
            return this.compensationValueField;
        }
        set {
            this.compensationValueField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ProfessionalDetail))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.capitaliq.com/CIQDotNet/Company/ProfessionalsDetail")]
public partial class ProfessionalBase {
    
    private int professionalIdField;
    
    private int companyIdField;
    
    private string companyNameField;
    
    private int boardStatusIdField;
    
    private int professionalStatusIdField;
    
    private bool alumniFlagField;
    
    /// <remarks/>
    public int ProfessionalId {
        get {
            return this.professionalIdField;
        }
        set {
            this.professionalIdField = value;
        }
    }
    
    /// <remarks/>
    public int CompanyId {
        get {
            return this.companyIdField;
        }
        set {
            this.companyIdField = value;
        }
    }
    
    /// <remarks/>
    public string CompanyName {
        get {
            return this.companyNameField;
        }
        set {
            this.companyNameField = value;
        }
    }
    
    /// <remarks/>
    public int BoardStatusId {
        get {
            return this.boardStatusIdField;
        }
        set {
            this.boardStatusIdField = value;
        }
    }
    
    /// <remarks/>
    public int ProfessionalStatusId {
        get {
            return this.professionalStatusIdField;
        }
        set {
            this.professionalStatusIdField = value;
        }
    }
    
    /// <remarks/>
    public bool AlumniFlag {
        get {
            return this.alumniFlagField;
        }
        set {
            this.alumniFlagField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void GetProfessionalsDetailCompletedEventHandler(object sender, GetProfessionalsDetailCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetProfessionalsDetailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetProfessionalsDetailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public Person[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((Person[])(this.results[0]));
        }
    }
}
