//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.42.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="GetCompanyRelationshipsSoap", Namespace="http://www.capitaliq.com/CIQDotNet/api/current/GetCompanyRelationships")]
public partial class GetCompanyRelationships : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback CallGetCompanyRelationshipsOperationCompleted;
    
    /// <remarks/>
    public GetCompanyRelationships() {
        this.Url = "https://api.capitaliq.com/ciqdotnet/api/current/GetCompanyRelationships.asmx";
    }
    
    /// <remarks/>
    public event CallGetCompanyRelationshipsCompletedEventHandler CallGetCompanyRelationshipsCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.capitaliq.com/CIQDotNet/api/current/GetCompanyRelationships/GetCompany" +
        "Relationships", RequestElementName="GetCompanyRelationships", RequestNamespace="http://www.capitaliq.com/CIQDotNet/api/current/GetCompanyRelationships", ResponseElementName="GetCompanyRelationshipsResponse", ResponseNamespace="http://www.capitaliq.com/CIQDotNet/api/current/GetCompanyRelationships", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlArrayAttribute("GetCompanyRelationshipsResult")]
    public CompanyRelationship[] CallGetCompanyRelationships(int[] CompanyId, int[] CompanyRelationshipTypeId, bool IncludeSubsidiariesFlag, bool IncludeInvestmentsFlag) {
        object[] results = this.Invoke("CallGetCompanyRelationships", new object[] {
                    CompanyId,
                    CompanyRelationshipTypeId,
                    IncludeSubsidiariesFlag,
                    IncludeInvestmentsFlag});
        return ((CompanyRelationship[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginCallGetCompanyRelationships(int[] CompanyId, int[] CompanyRelationshipTypeId, bool IncludeSubsidiariesFlag, bool IncludeInvestmentsFlag, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("CallGetCompanyRelationships", new object[] {
                    CompanyId,
                    CompanyRelationshipTypeId,
                    IncludeSubsidiariesFlag,
                    IncludeInvestmentsFlag}, callback, asyncState);
    }
    
    /// <remarks/>
    public CompanyRelationship[] EndCallGetCompanyRelationships(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((CompanyRelationship[])(results[0]));
    }
    
    /// <remarks/>
    public void CallGetCompanyRelationshipsAsync(int[] CompanyId, int[] CompanyRelationshipTypeId, bool IncludeSubsidiariesFlag, bool IncludeInvestmentsFlag) {
        this.CallGetCompanyRelationshipsAsync(CompanyId, CompanyRelationshipTypeId, IncludeSubsidiariesFlag, IncludeInvestmentsFlag, null);
    }
    
    /// <remarks/>
    public void CallGetCompanyRelationshipsAsync(int[] CompanyId, int[] CompanyRelationshipTypeId, bool IncludeSubsidiariesFlag, bool IncludeInvestmentsFlag, object userState) {
        if ((this.CallGetCompanyRelationshipsOperationCompleted == null)) {
            this.CallGetCompanyRelationshipsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCallGetCompanyRelationshipsOperationCompleted);
        }
        this.InvokeAsync("CallGetCompanyRelationships", new object[] {
                    CompanyId,
                    CompanyRelationshipTypeId,
                    IncludeSubsidiariesFlag,
                    IncludeInvestmentsFlag}, this.CallGetCompanyRelationshipsOperationCompleted, userState);
    }
    
    private void OnCallGetCompanyRelationshipsOperationCompleted(object arg) {
        if ((this.CallGetCompanyRelationshipsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.CallGetCompanyRelationshipsCompleted(this, new CallGetCompanyRelationshipsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.capitaliq.com/CIQDotNet/api/current/GetCompanyRelationships")]
public partial class CompanyRelationship {
    
    private int inputCompanyIdField;
    
    private int companyRelIdField;
    
    private int companyRelationshipTypeIdField;
    
    private string companyRelationshipTypeNameField;
    
    private int companyId1Field;
    
    private string companyName1Field;
    
    private int companyId2Field;
    
    private string companyName2Field;
    
    private int companyTypeId2Field;
    
    private string companyTypeName2Field;
    
    private int companyStatusTypeId2Field;
    
    private string companyStatusTypeName2Field;
    
    private string businessDescription2Field;
    
    /// <remarks/>
    public int InputCompanyId {
        get {
            return this.inputCompanyIdField;
        }
        set {
            this.inputCompanyIdField = value;
        }
    }
    
    /// <remarks/>
    public int CompanyRelId {
        get {
            return this.companyRelIdField;
        }
        set {
            this.companyRelIdField = value;
        }
    }
    
    /// <remarks/>
    public int CompanyRelationshipTypeId {
        get {
            return this.companyRelationshipTypeIdField;
        }
        set {
            this.companyRelationshipTypeIdField = value;
        }
    }
    
    /// <remarks/>
    public string CompanyRelationshipTypeName {
        get {
            return this.companyRelationshipTypeNameField;
        }
        set {
            this.companyRelationshipTypeNameField = value;
        }
    }
    
    /// <remarks/>
    public int CompanyId1 {
        get {
            return this.companyId1Field;
        }
        set {
            this.companyId1Field = value;
        }
    }
    
    /// <remarks/>
    public string CompanyName1 {
        get {
            return this.companyName1Field;
        }
        set {
            this.companyName1Field = value;
        }
    }
    
    /// <remarks/>
    public int CompanyId2 {
        get {
            return this.companyId2Field;
        }
        set {
            this.companyId2Field = value;
        }
    }
    
    /// <remarks/>
    public string CompanyName2 {
        get {
            return this.companyName2Field;
        }
        set {
            this.companyName2Field = value;
        }
    }
    
    /// <remarks/>
    public int CompanyTypeId2 {
        get {
            return this.companyTypeId2Field;
        }
        set {
            this.companyTypeId2Field = value;
        }
    }
    
    /// <remarks/>
    public string CompanyTypeName2 {
        get {
            return this.companyTypeName2Field;
        }
        set {
            this.companyTypeName2Field = value;
        }
    }
    
    /// <remarks/>
    public int CompanyStatusTypeId2 {
        get {
            return this.companyStatusTypeId2Field;
        }
        set {
            this.companyStatusTypeId2Field = value;
        }
    }
    
    /// <remarks/>
    public string CompanyStatusTypeName2 {
        get {
            return this.companyStatusTypeName2Field;
        }
        set {
            this.companyStatusTypeName2Field = value;
        }
    }
    
    /// <remarks/>
    public string BusinessDescription2 {
        get {
            return this.businessDescription2Field;
        }
        set {
            this.businessDescription2Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void CallGetCompanyRelationshipsCompletedEventHandler(object sender, CallGetCompanyRelationshipsCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CallGetCompanyRelationshipsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal CallGetCompanyRelationshipsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public CompanyRelationship[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((CompanyRelationship[])(this.results[0]));
        }
    }
}
