//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.42.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="KeyDevDataSoap", Namespace="https://www.capitaliq.com/CIQDotNet/KeyDevs/KeyDevData")]
public partial class KeyDevData : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback GetKeyDevelopmentsOperationCompleted;
    
    /// <remarks/>
    public KeyDevData() {
        this.Url = "https://api.capitaliq.com/ciqdotnet/api/current/KeyDevelopments.asmx";
    }
    
    /// <remarks/>
    public event GetKeyDevelopmentsCompletedEventHandler GetKeyDevelopmentsCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.capitaliq.com/CIQDotNet/KeyDevs/KeyDevData/GetKeyDevelopments", RequestNamespace="https://www.capitaliq.com/CIQDotNet/KeyDevs/KeyDevData", ResponseNamespace="https://www.capitaliq.com/CIQDotNet/KeyDevs/KeyDevData", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public KeyDevelopment[] GetKeyDevelopments(int[] InCompanyIdList, System.DateTime InStartDateUTC, System.DateTime InEndDateUTC, int[] InKeyDevEventTypeIdList, bool InIncludeSubsidiariesFlag, bool InIncludeInvestmentsFlag) {
        object[] results = this.Invoke("GetKeyDevelopments", new object[] {
                    InCompanyIdList,
                    InStartDateUTC,
                    InEndDateUTC,
                    InKeyDevEventTypeIdList,
                    InIncludeSubsidiariesFlag,
                    InIncludeInvestmentsFlag});
        return ((KeyDevelopment[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetKeyDevelopments(int[] InCompanyIdList, System.DateTime InStartDateUTC, System.DateTime InEndDateUTC, int[] InKeyDevEventTypeIdList, bool InIncludeSubsidiariesFlag, bool InIncludeInvestmentsFlag, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetKeyDevelopments", new object[] {
                    InCompanyIdList,
                    InStartDateUTC,
                    InEndDateUTC,
                    InKeyDevEventTypeIdList,
                    InIncludeSubsidiariesFlag,
                    InIncludeInvestmentsFlag}, callback, asyncState);
    }
    
    /// <remarks/>
    public KeyDevelopment[] EndGetKeyDevelopments(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((KeyDevelopment[])(results[0]));
    }
    
    /// <remarks/>
    public void GetKeyDevelopmentsAsync(int[] InCompanyIdList, System.DateTime InStartDateUTC, System.DateTime InEndDateUTC, int[] InKeyDevEventTypeIdList, bool InIncludeSubsidiariesFlag, bool InIncludeInvestmentsFlag) {
        this.GetKeyDevelopmentsAsync(InCompanyIdList, InStartDateUTC, InEndDateUTC, InKeyDevEventTypeIdList, InIncludeSubsidiariesFlag, InIncludeInvestmentsFlag, null);
    }
    
    /// <remarks/>
    public void GetKeyDevelopmentsAsync(int[] InCompanyIdList, System.DateTime InStartDateUTC, System.DateTime InEndDateUTC, int[] InKeyDevEventTypeIdList, bool InIncludeSubsidiariesFlag, bool InIncludeInvestmentsFlag, object userState) {
        if ((this.GetKeyDevelopmentsOperationCompleted == null)) {
            this.GetKeyDevelopmentsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetKeyDevelopmentsOperationCompleted);
        }
        this.InvokeAsync("GetKeyDevelopments", new object[] {
                    InCompanyIdList,
                    InStartDateUTC,
                    InEndDateUTC,
                    InKeyDevEventTypeIdList,
                    InIncludeSubsidiariesFlag,
                    InIncludeInvestmentsFlag}, this.GetKeyDevelopmentsOperationCompleted, userState);
    }
    
    private void OnGetKeyDevelopmentsOperationCompleted(object arg) {
        if ((this.GetKeyDevelopmentsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetKeyDevelopmentsCompleted(this, new GetKeyDevelopmentsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.capitaliq.com/CIQDotNet/KeyDevs/KeyDevData")]
public partial class KeyDevelopment {
    
    private string headlineField;
    
    private string situationField;
    
    private System.DateTime keyDevelopmentDateUTCField;
    
    private System.DateTime lastModifiedDateUTCField;
    
    private KeyDevCompanyEventTypeData[] keyDevCompanyEventTypeDataListField;
    
    /// <remarks/>
    public string Headline {
        get {
            return this.headlineField;
        }
        set {
            this.headlineField = value;
        }
    }
    
    /// <remarks/>
    public string Situation {
        get {
            return this.situationField;
        }
        set {
            this.situationField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime KeyDevelopmentDateUTC {
        get {
            return this.keyDevelopmentDateUTCField;
        }
        set {
            this.keyDevelopmentDateUTCField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime LastModifiedDateUTC {
        get {
            return this.lastModifiedDateUTCField;
        }
        set {
            this.lastModifiedDateUTCField = value;
        }
    }
    
    /// <remarks/>
    public KeyDevCompanyEventTypeData[] KeyDevCompanyEventTypeDataList {
        get {
            return this.keyDevCompanyEventTypeDataListField;
        }
        set {
            this.keyDevCompanyEventTypeDataListField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.capitaliq.com/CIQDotNet/KeyDevs/KeyDevData")]
public partial class KeyDevCompanyEventTypeData {
    
    private int companyIdField;
    
    private string companyNameField;
    
    private int roleTypeIdField;
    
    private int parentCompanyIdField;
    
    private string parentCompanyNameField;
    
    private string relationshipTypeNameField;
    
    private int keyDevelopmentEventTypeIdField;
    
    /// <remarks/>
    public int CompanyId {
        get {
            return this.companyIdField;
        }
        set {
            this.companyIdField = value;
        }
    }
    
    /// <remarks/>
    public string CompanyName {
        get {
            return this.companyNameField;
        }
        set {
            this.companyNameField = value;
        }
    }
    
    /// <remarks/>
    public int RoleTypeId {
        get {
            return this.roleTypeIdField;
        }
        set {
            this.roleTypeIdField = value;
        }
    }
    
    /// <remarks/>
    public int ParentCompanyId {
        get {
            return this.parentCompanyIdField;
        }
        set {
            this.parentCompanyIdField = value;
        }
    }
    
    /// <remarks/>
    public string ParentCompanyName {
        get {
            return this.parentCompanyNameField;
        }
        set {
            this.parentCompanyNameField = value;
        }
    }
    
    /// <remarks/>
    public string RelationshipTypeName {
        get {
            return this.relationshipTypeNameField;
        }
        set {
            this.relationshipTypeNameField = value;
        }
    }
    
    /// <remarks/>
    public int KeyDevelopmentEventTypeId {
        get {
            return this.keyDevelopmentEventTypeIdField;
        }
        set {
            this.keyDevelopmentEventTypeIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void GetKeyDevelopmentsCompletedEventHandler(object sender, GetKeyDevelopmentsCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetKeyDevelopmentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetKeyDevelopmentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public KeyDevelopment[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((KeyDevelopment[])(this.results[0]));
        }
    }
}
