//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.42.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="GetBusinessRelationshipsSoap", Namespace="http://www.capitaliq.com/CIQDotNet/api/current/GetBusinessRelationships")]
public partial class GetBusinessRelationships : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback CallGetBusinessRelationshipsOperationCompleted;
    
    /// <remarks/>
    public GetBusinessRelationships() {
        this.Url = "https://api.capitaliq.com/ciqdotnet/api/current/GetBusinessRelationships.asmx";
    }
    
    /// <remarks/>
    public event CallGetBusinessRelationshipsCompletedEventHandler CallGetBusinessRelationshipsCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.capitaliq.com/CIQDotNet/api/current/GetBusinessRelationships/GetBusine" +
        "ssRelationships", RequestElementName="GetBusinessRelationships", RequestNamespace="http://www.capitaliq.com/CIQDotNet/api/current/GetBusinessRelationships", ResponseElementName="GetBusinessRelationshipsResponse", ResponseNamespace="http://www.capitaliq.com/CIQDotNet/api/current/GetBusinessRelationships", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlArrayAttribute("GetBusinessRelationshipsResult")]
    public BusinessRelationship[] CallGetBusinessRelationships(int[] CompanyId, int[] BusinessRelationshipTypeId, bool IncludeSubsidiariesFlag, bool IncludeInvestmentsFlag, bool IncludePriorFlag) {
        object[] results = this.Invoke("CallGetBusinessRelationships", new object[] {
                    CompanyId,
                    BusinessRelationshipTypeId,
                    IncludeSubsidiariesFlag,
                    IncludeInvestmentsFlag,
                    IncludePriorFlag});
        return ((BusinessRelationship[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginCallGetBusinessRelationships(int[] CompanyId, int[] BusinessRelationshipTypeId, bool IncludeSubsidiariesFlag, bool IncludeInvestmentsFlag, bool IncludePriorFlag, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("CallGetBusinessRelationships", new object[] {
                    CompanyId,
                    BusinessRelationshipTypeId,
                    IncludeSubsidiariesFlag,
                    IncludeInvestmentsFlag,
                    IncludePriorFlag}, callback, asyncState);
    }
    
    /// <remarks/>
    public BusinessRelationship[] EndCallGetBusinessRelationships(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((BusinessRelationship[])(results[0]));
    }
    
    /// <remarks/>
    public void CallGetBusinessRelationshipsAsync(int[] CompanyId, int[] BusinessRelationshipTypeId, bool IncludeSubsidiariesFlag, bool IncludeInvestmentsFlag, bool IncludePriorFlag) {
        this.CallGetBusinessRelationshipsAsync(CompanyId, BusinessRelationshipTypeId, IncludeSubsidiariesFlag, IncludeInvestmentsFlag, IncludePriorFlag, null);
    }
    
    /// <remarks/>
    public void CallGetBusinessRelationshipsAsync(int[] CompanyId, int[] BusinessRelationshipTypeId, bool IncludeSubsidiariesFlag, bool IncludeInvestmentsFlag, bool IncludePriorFlag, object userState) {
        if ((this.CallGetBusinessRelationshipsOperationCompleted == null)) {
            this.CallGetBusinessRelationshipsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCallGetBusinessRelationshipsOperationCompleted);
        }
        this.InvokeAsync("CallGetBusinessRelationships", new object[] {
                    CompanyId,
                    BusinessRelationshipTypeId,
                    IncludeSubsidiariesFlag,
                    IncludeInvestmentsFlag,
                    IncludePriorFlag}, this.CallGetBusinessRelationshipsOperationCompleted, userState);
    }
    
    private void OnCallGetBusinessRelationshipsOperationCompleted(object arg) {
        if ((this.CallGetBusinessRelationshipsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.CallGetBusinessRelationshipsCompleted(this, new CallGetBusinessRelationshipsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.capitaliq.com/CIQDotNet/api/current/GetBusinessRelationships")]
public partial class BusinessRelationship {
    
    private int inputCompanyIdField;
    
    private string inputCompanyNameField;
    
    private int companyId1Field;
    
    private string companyName1Field;
    
    private int companyId2Field;
    
    private string companyName2Field;
    
    private int businessRelationshipTypeIdField;
    
    private string businessRelationshipTypeNameField;
    
    private bool priorFlagField;
    
    private int businessRelationshipSourceTypeIdField;
    
    private string businessRelationshipSourceTypeNameField;
    
    private string simpleIndustryIdField;
    
    private string simpleIndustryNameField;
    
    private string sectorIdField;
    
    private string sectorNameField;
    
    private string industryGroupIdField;
    
    private string industryGroupNameField;
    
    private string industryIdField;
    
    private string industryNameField;
    
    private string subIndustryIdField;
    
    private string subIndustryNameField;
    
    /// <remarks/>
    public int InputCompanyId {
        get {
            return this.inputCompanyIdField;
        }
        set {
            this.inputCompanyIdField = value;
        }
    }
    
    /// <remarks/>
    public string InputCompanyName {
        get {
            return this.inputCompanyNameField;
        }
        set {
            this.inputCompanyNameField = value;
        }
    }
    
    /// <remarks/>
    public int CompanyId1 {
        get {
            return this.companyId1Field;
        }
        set {
            this.companyId1Field = value;
        }
    }
    
    /// <remarks/>
    public string CompanyName1 {
        get {
            return this.companyName1Field;
        }
        set {
            this.companyName1Field = value;
        }
    }
    
    /// <remarks/>
    public int CompanyId2 {
        get {
            return this.companyId2Field;
        }
        set {
            this.companyId2Field = value;
        }
    }
    
    /// <remarks/>
    public string CompanyName2 {
        get {
            return this.companyName2Field;
        }
        set {
            this.companyName2Field = value;
        }
    }
    
    /// <remarks/>
    public int BusinessRelationshipTypeId {
        get {
            return this.businessRelationshipTypeIdField;
        }
        set {
            this.businessRelationshipTypeIdField = value;
        }
    }
    
    /// <remarks/>
    public string BusinessRelationshipTypeName {
        get {
            return this.businessRelationshipTypeNameField;
        }
        set {
            this.businessRelationshipTypeNameField = value;
        }
    }
    
    /// <remarks/>
    public bool PriorFlag {
        get {
            return this.priorFlagField;
        }
        set {
            this.priorFlagField = value;
        }
    }
    
    /// <remarks/>
    public int BusinessRelationshipSourceTypeId {
        get {
            return this.businessRelationshipSourceTypeIdField;
        }
        set {
            this.businessRelationshipSourceTypeIdField = value;
        }
    }
    
    /// <remarks/>
    public string BusinessRelationshipSourceTypeName {
        get {
            return this.businessRelationshipSourceTypeNameField;
        }
        set {
            this.businessRelationshipSourceTypeNameField = value;
        }
    }
    
    /// <remarks/>
    public string SimpleIndustryId {
        get {
            return this.simpleIndustryIdField;
        }
        set {
            this.simpleIndustryIdField = value;
        }
    }
    
    /// <remarks/>
    public string SimpleIndustryName {
        get {
            return this.simpleIndustryNameField;
        }
        set {
            this.simpleIndustryNameField = value;
        }
    }
    
    /// <remarks/>
    public string SectorId {
        get {
            return this.sectorIdField;
        }
        set {
            this.sectorIdField = value;
        }
    }
    
    /// <remarks/>
    public string SectorName {
        get {
            return this.sectorNameField;
        }
        set {
            this.sectorNameField = value;
        }
    }
    
    /// <remarks/>
    public string IndustryGroupId {
        get {
            return this.industryGroupIdField;
        }
        set {
            this.industryGroupIdField = value;
        }
    }
    
    /// <remarks/>
    public string IndustryGroupName {
        get {
            return this.industryGroupNameField;
        }
        set {
            this.industryGroupNameField = value;
        }
    }
    
    /// <remarks/>
    public string IndustryId {
        get {
            return this.industryIdField;
        }
        set {
            this.industryIdField = value;
        }
    }
    
    /// <remarks/>
    public string IndustryName {
        get {
            return this.industryNameField;
        }
        set {
            this.industryNameField = value;
        }
    }
    
    /// <remarks/>
    public string SubIndustryId {
        get {
            return this.subIndustryIdField;
        }
        set {
            this.subIndustryIdField = value;
        }
    }
    
    /// <remarks/>
    public string SubIndustryName {
        get {
            return this.subIndustryNameField;
        }
        set {
            this.subIndustryNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void CallGetBusinessRelationshipsCompletedEventHandler(object sender, CallGetBusinessRelationshipsCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CallGetBusinessRelationshipsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal CallGetBusinessRelationshipsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public BusinessRelationship[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((BusinessRelationship[])(this.results[0]));
        }
    }
}
